# Generated by Django 4.1 on 2024-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '管理者',
                'verbose_name_plural': '管理者',
                'ordering': ['-admin_id'],
            },
        ),
    ]
