# Generated by Django 4.1 on 2024-07-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_initial'),
    ]

    operations = [
    ]
