# Generated by Django 2.1 on 2024-07-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
