# Generated by Django 4.1 on 2024-07-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240717_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-user_id'], 'verbose_name': 'ユーザ', 'verbose_name_plural': 'ユーザ'},
        ),
    ]
